//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Azure.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Azure.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;feed xml:base=&quot;http://myaccount.tables.core.windows.net/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Customers&lt;/title&gt;
        ///  &lt;id&gt;http://myaccount.tables.core.windows.net/Customers&lt;/id&gt;
        ///  &lt;updated&gt;2008-10-01T15:26:13Z&lt;/updated&gt;
        ///  &lt;link rel=&quot;self&quot; title=&quot;Customers&quot; href=&quot;Customers&quot; /&gt;
        ///  &lt;entry m:etag=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryEntitiesResponseText {
            get {
                return ResourceManager.GetString("QueryEntitiesResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;feed xml:base=&quot;http://myaccount.tables.core.windows.net/&quot; 
        ///      xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; 
        ///	  xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; 
        ///	  xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Tables&lt;/title&gt;
        ///  &lt;id&gt;http://myaccount.tables.core.windows.net/Tables&lt;/id&gt;
        ///  &lt;updated&gt;2009-01-04T17:18:54.7062347Z&lt;/updated&gt;
        ///  &lt;link rel=&quot;self&quot; title=&quot;Tables&quot; href=&quot;Tables&quot; /&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryTablesResponseText {
            get {
                return ResourceManager.GetString("QueryTablesResponseText", resourceCulture);
            }
        }
    }
}
